In [1]:
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [4]:
dataset = pd.read_csv('User_Data.csv')
x = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [6]:
type(x_train)

numpy.ndarray

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [8]:
mn=MinMaxScaler()
x_train2 = mn.fit_transform(x_train)
x_test2 = mn.transform(x_test)

In [9]:
sc = StandardScaler()
x_train1 = sc.fit_transform(x_train)
x_test1 = sc.transform(x_test)

In [10]:
print(x_train1)

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 [ 0.08648817  0.76590222]
 

In [11]:
print(x_train2)

[[0.61904762 0.17777778]
 [0.33333333 0.77777778]
 [0.47619048 0.25925926]
 [0.33333333 0.88888889]
 [0.80952381 0.04444444]
 [0.83333333 0.65925926]
 [0.5        0.2       ]
 [0.47619048 0.34074074]
 [0.42857143 0.25925926]
 [0.42857143 0.35555556]
 [0.4047619  0.07407407]
 [0.4047619  0.25925926]
 [0.57142857 0.42962963]
 [0.69047619 0.25185185]
 [0.97619048 0.1037037 ]
 [0.73809524 0.37037037]
 [0.64285714 0.85925926]
 [0.30952381 0.54814815]
 [0.66666667 0.4962963 ]
 [0.69047619 0.26666667]
 [0.19047619 0.        ]
 [1.         0.64444444]
 [0.47619048 0.71851852]
 [0.52380952 0.68148148]
 [0.57142857 0.28148148]
 [0.4047619  0.32592593]
 [0.71428571 0.19259259]
 [0.71428571 0.88148148]
 [0.47619048 0.72592593]
 [0.26190476 0.98518519]
 [0.19047619 0.        ]
 [1.         0.2       ]
 [0.14285714 0.02962963]
 [0.57142857 0.99259259]
 [0.66666667 0.6       ]
 [0.23809524 0.32592593]
 [0.5        0.6       ]
 [0.23809524 0.54814815]
 [0.54761905 0.42222222]
 [0.64285714 0.08148148]


In [12]:
dff=pd.concat([pd.DataFrame(x_train1,columns=['a','b']),pd.DataFrame(x_train2,columns=['a','b'])],axis=1)
dff

a         b         a         b
0    0.581649 -0.886707  0.619048  0.177778
1   -0.606738  1.461738  0.333333  0.777778
2   -0.012544 -0.567782  0.476190  0.259259
3   -0.606738  1.896635  0.333333  0.888889
4    1.373907 -1.408584  0.809524  0.044444
..        ...       ...       ...       ...
295  0.977778 -1.147645  0.714286  0.111111
296 -0.903834 -0.770734  0.261905  0.207407
297 -0.210609 -0.509796  0.428571  0.274074
298 -1.101899 -0.451810  0.214286  0.288889
299 -1.200931  1.403751  0.190476  0.762963

[300 rows x 4 columns]

In [13]:
print(x_test1)

[[-0.80480212  0.50496393]
 [-0.01254409 -0.5677824 ]
 [-0.30964085  0.1570462 ]
 [-0.80480212  0.27301877]
 [-0.30964085 -0.5677824 ]
 [-1.10189888 -1.43757673]
 [-0.70576986 -1.58254245]
 [-0.21060859  2.15757314]
 [-1.99318916 -0.04590581]
 [ 0.8787462  -0.77073441]
 [-0.80480212 -0.59677555]
 [-1.00286662 -0.42281668]
 [-0.11157634 -0.42281668]
 [ 0.08648817  0.21503249]
 [-1.79512465  0.47597078]
 [-0.60673761  1.37475825]
 [-0.11157634  0.21503249]
 [-1.89415691  0.44697764]
 [ 1.67100423  1.75166912]
 [-0.30964085 -1.37959044]
 [-0.30964085 -0.65476184]
 [ 0.8787462   2.15757314]
 [ 0.28455268 -0.53878926]
 [ 0.8787462   1.02684052]
 [-1.49802789 -1.20563157]
 [ 1.07681071  2.07059371]
 [-1.00286662  0.50496393]
 [-0.90383437  0.30201192]
 [-0.11157634 -0.21986468]
 [-0.60673761  0.47597078]
 [-1.6960924   0.53395707]
 [-0.11157634  0.27301877]
 [ 1.86906873 -0.27785096]
 [-0.11157634 -0.48080297]
 [-1.39899564 -0.33583725]
 [-1.99318916 -0.50979612]
 [-1.59706014  0.33100506]
 

In [14]:
print(x_test2)

[[0.28571429 0.53333333]
 [0.47619048 0.25925926]
 [0.4047619  0.44444444]
 [0.28571429 0.47407407]
 [0.4047619  0.25925926]
 [0.21428571 0.03703704]
 [0.30952381 0.        ]
 [0.42857143 0.95555556]
 [0.         0.39259259]
 [0.69047619 0.20740741]
 [0.28571429 0.25185185]
 [0.23809524 0.2962963 ]
 [0.45238095 0.2962963 ]
 [0.5        0.45925926]
 [0.04761905 0.52592593]
 [0.33333333 0.75555556]
 [0.45238095 0.45925926]
 [0.02380952 0.51851852]
 [0.88095238 0.85185185]
 [0.4047619  0.05185185]
 [0.4047619  0.23703704]
 [0.69047619 0.95555556]
 [0.54761905 0.26666667]
 [0.69047619 0.66666667]
 [0.11904762 0.0962963 ]
 [0.73809524 0.93333333]
 [0.23809524 0.53333333]
 [0.26190476 0.48148148]
 [0.45238095 0.34814815]
 [0.33333333 0.52592593]
 [0.07142857 0.54074074]
 [0.45238095 0.47407407]
 [0.92857143 0.33333333]
 [0.45238095 0.28148148]
 [0.14285714 0.31851852]
 [0.         0.27407407]
 [0.0952381  0.48888889]
 [0.38095238 0.20740741]
 [0.30952381 0.14074074]
 [0.73809524 0.15555556]


In [15]:
dff1=pd.concat([pd.DataFrame(x_test1,columns=['a','b']),pd.DataFrame(x_test2,columns=['a','b'])],axis=1)
dff1

a         b         a         b
0  -0.804802  0.504964  0.285714  0.533333
1  -0.012544 -0.567782  0.476190  0.259259
2  -0.309641  0.157046  0.404762  0.444444
3  -0.804802  0.273019  0.285714  0.474074
4  -0.309641 -0.567782  0.404762  0.259259
..       ...       ...       ...       ...
95 -1.101899  0.765902  0.214286  0.600000
96 -1.498028 -0.190872  0.119048  0.355556
97  0.977778 -1.060666  0.714286  0.133333
98  0.977778  0.591943  0.714286  0.555556
99  0.383585  0.997847  0.571429  0.659259

[100 rows x 4 columns]

In [16]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(dff, y_train)

GaussianNB()

In [17]:
y_pred = classifier.predict(dff1)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]


In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix : \n",cm)

Confusion Matrix : 
 [[64  4]
 [ 4 28]]
